

poison_target_label: 0
scale_weights_poison: 1
poison_epochs: [[0,3000]]


eta: 0.1
trigger_num: 4

# gap 3 size 1*6 base (0, 0)
img_poison_patterns: [[[0, 0], [0, 1], [0, 2], [0, 3], [0, 4], [0, 5]],
[[0, 9], [0, 10], [0, 11], [0, 12], [0, 13], [0, 14]],
[[4, 0], [4, 1], [4, 2], [4, 3], [4, 4], [4, 5]],
[[4, 9], [4, 10], [4, 11], [4, 12], [4, 13], [4, 14]]]


text_poison_patterns: ["cf","tq","mn","mb"]  # ["cf","tq","mn","bb","mb"]

tabular_poison_patterns: [[1,2],[4,5]]





