---
atk_type: opt
atk_name: see_thru_grads
# Set the target number of pic to reconstruct 
num2recovery: 32
# Choose one round to carry out attack
atk_round: 1
# Number of training epochs before attack(Not use now)
warm_up: 50
# Number of epochs to reconstruct a sample
num_trials: 20000
optim: adam
lr: 0.01
cost_fn: Euclidean
cost_scale: 0.0001

regularization:
  TV: 0.0001
  L2: 1e-06

scheduler:
  CosineAnnealingLR
signed: False
# Choose the victim client 
cid: 0
tid:
# Number of Images to be recovered from the given gradient
num_imgs: 8
# Way to infer label
label_inf: iDLG
# Choice of image initialization
init_img: rand
# Set the frequency of print loss and save image
print_interval: 1000